name: PR Checks without Testing
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
    
jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run:
          echo "Hello World!"
    
  lint-tests:
    name: PyLint Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - name: Checkout code
      - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Python venv
      id: cache-python
      uses: actions/cache@v3
      with:
        path: .venv  # Path to the virtual environment
        key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-
  
    - name: Create venv if not cached
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: |
        python -m venv .venv
        . .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        # Install FLIR pyspin from the wheel file
        pip install ./pyspin_wheel/spinnaker_python-4.0.0.116-cp38-cp38-win_amd64.whl
      shell: bash
      
    - name: Use cached venv
      if: steps.cache-python.outputs.cache-hit == 'true'
      run: |
        . .venv/bin/activate
      shell: bash

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  all-checks-passed: 
    name: All Checks Passed 
    if: always()
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Ensure all required jobs pass successfully
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  auto-merge:
    name: Auto-Merge Admin PR After All Checks Passed
    if: success() && ${{ contains(fromJson('["bebo1010"]'), github.actor) }}
    needs: all-checks-passed
    runs-on: ubuntu-latest
    steps:
      - name: Create github app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.AUTO_MERGE_BOT_APP_ID }}
          private-key: ${{ secrets.AUTO_MERGE_BOT_PRIVATE_KEY }}

      - name: Approve and squash the pull request
        env: 
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{github.event.pull_request.html_url}}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --admin -s "$PR_URL"
